### ISSUE TITLE
Compiled version 

### ISSUE THREAD

**Issue by yashine59fr** [DarthTon/Blackbone#119]
Is it possible to create a compiled version ?
Idk why it say me when I load driver an error message.

**Comment by clayfrocker97** [comment]
You're an idiot

**Comment by Houd1ny** [comment]
Maybe I`m fool, but author of issue maybe was talking about dynamic library for this library.
I have found Visual studio build configuration "Release(DLL)"
It`s is fine.
But I have found another problem with including library headers.
For example I need just one feature
class VTableDetour
to use this class in the end I was forced to include contrib that is the same lvl as src folder.
Actuality I copied all repository.
Is this possible to move including of some config or 3rd party headers to source file?
So that it will be possible to include only some(1-10) api header files and Blackbone dll(with related dlls) in project that want to use library.
As i say maybe I `m doing something wrong, but how not to include all project source code.

**Comment by Houd1ny** [comment]
Actually right now i`m getting error
"error: C2440: 'return' : cannot convert from 'const asmjit::X86GpReg' to 'asmjit::Error'
No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called"

**Comment by DarthTon** [comment]
It's unlikely to happen because whole hooking subsystem eventually end in some template code that relies on AsmJit and is hard to properly abstract in source files only.
