### ISSUE TITLE
Win 10 version 1903 - LdrpHandleTlsData offset changed 

### ISSUE THREAD

**Issue by MINIONBOTS** [DarthTon/Blackbone#345]
The LdrpHandleTlsData offset for the newest win 10 version is now 0x46:

![image](https://user-images.githubusercontent.com/2842405/57016929-01b4fa80-6c1d-11e9-999a-6aef1b70dc92.png)

Thanks for your lovely work <3

**Comment by MINIONBOTS** [comment]
Version is 
Build_RS6 = 18362, // 18362.86

**Comment by MINIONBOTS** [comment]
I cannot really test it myself, if that change was the only one, but maybe someone else can ?
[ntdll.zip](https://github.com/DarthTon/Blackbone/files/3136995/ntdll.zip)

**Comment by DarthTon** [comment]
I'll wait until update is officially rolled out.

**Comment by Blick1337** [comment]
> I'll wait until update is officially rolled out.

update released. ntdll if you need 
[ntdll_1903.zip](https://github.com/DarthTon/Blackbone/files/3233185/ntdll_1903.zip)

**Comment by qlael50** [comment]
@MINIONBOTS, i have found this region here

`auto offset = IsWindows10RS4OrGreater() ? 0x46 : 0x43; //0x44 : 0x43`

changed from 0x44 to 0x46 like your comment and that does not appear to solve my current issue for windows 10 build 1903 it crashes the application that I try to inject into (MMap usermode injection which works for everything except windows 10 build 1903)

did I do something wrong or should we all just wait for @DarthTon to update?

**Comment by MINIONBOTS** [comment]
This is all we changed and it works right now :
![image](https://user-images.githubusercontent.com/2842405/59016586-dc319700-8841-11e9-864b-3e73c4df3630.png)

**Comment by qlael50** [comment]
@MINIONBOTS,

I have latest visual studios 2019 updated and rebuilt the blackbone project inside my test project and updated the blackbone lib with this but I think that the problem lies somewhere else as it still crashes the application you inject into on 1903. 

I have a small test DLL that beeps once - it is converted to a byte array and using the `test.mmap().MapImage()` method which works fine on all other supported windows but not on 1903 it just crashes the target application.

I have tested loading the same DLL from memory using the byte array with an old injector of mine and it works on 1903 so there is something else causing the issue on blackbone, its just that i prefer using blackbone as it has alot more functionality.

Would you mind running a similar scenario? Here is the DLL code if youd like


`void StartThread()
{
	Beep(800, 100);
}

BOOL WINAPI DllMain(_In_ HINSTANCE hinstDLL, _In_ DWORD fdwReason, _In_ LPVOID lpvReserved)
{
	switch (fdwReason)
	{
	case DLL_PROCESS_ATTACH:
		if (hinstDLL)
		{
			//DisableThreadLibraryCalls(hinstDLL);
			//ErasePEHeader(hinstDLL);
			//EraseHeaders(hinstDLL);
			CreateThread(nullptr, 0, reinterpret_cast<LPTHREAD_START_ROUTINE>(StartThread), hinstDLL, 0, nullptr);
		}
		break;
	}

	return TRUE;
}`
