### ISSUE TITLE
Issues manual mapping protected DLL on windows 10

### ISSUE THREAD

**Issue by Immortalety** [DarthTon/Blackbone#411]
Since I installed the 2004 version of windows 10, Blackbone stopped injecting protected DLLs (VMProtect or Themida with any settings). The target process crashes and the injector freezes at this point in function "ExecInWorkerThread" (then "ExecInAnyThread" if hijacking): MapImageInternal->RunModuleInitializers->ExecInWorkerThread(->ExecInAnyThread)->WaitForSingleObject. https://imgur.com/a/8n3nLi6

**Comment by dinrise** [comment]
i fix with that pull #398

**Comment by idkp** [comment]
Some of my customers experience the same problem. Making the code changes that were suggested by that pull request did not fix the issue. `WaitForSingleObject` apparently never returns in these cases.

**Comment by idkp** [comment]
@DarthTon

**Comment by DarthTon** [comment]
I'll look into this once I get my hands on 2004 update.

**Comment by idkp** [comment]
I had this problem with the `18362.836` version of Windows 10.

**Comment by RatTrap1337** [comment]
@DarthTon i spotted the issue here: 

![grafik](https://user-images.githubusercontent.com/35176106/83936639-bb3db200-a7c5-11ea-9c6c-0ffe85075862.png)

After the native call the process is gone. 

@Immortalety @idkp i also noticed that the "Sample" programm just works fine for me, on 2004 maybe its a issue due to your project settings? 

- activate sdl checks if you dont have it
- activate seh exceptions 
- use c++:latest
- try disable incremental linking
- disable standard c conformance mode 

that's what the Sample programm uses, also try to recompile blackbone with the latest sdk.

Theres no issue with the native call or the UserApc so far since its working for the other calls on it.
I also checked the exports in IDA theres nothing new. :o

**Comment by DarthTon** [comment]
Test dlls and exes fork for me on 2004, so I'd need your sample dll to check it further.
